version: "2"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

volumes:
  keys:

services:

  keys:
    image: airtonix/concourse-certs-generator:0.0.4
    tty: true
    stdin_open: true
    command: cat
    volumes:
      - keys:/concourse-keys

  db:
    hostname: concourse-db
    image: postgres:9.5
    restart: unless-stopped
    networks:
      - back
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
      PGDATA: /database

  tsa:
    container_name: concourse
    hostname: concourse
    image: concourse/concourse
    restart: unless-stopped
    command: web
    networks:
      - reverse-proxy
      - back
    ports:
      - "2222:2222"
    expose:
      - 2222
      - 8080
    volumes:
      - keys:/concourse-keys
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: concourse
      CONCOURSE_EXTERNAL_URL: ci.docker
      CONCOURSE_POSTGRES_DATA_SOURCE: postgres://concourse:concourse@db:5432/concourse?sslmode=disable
      VIRTUAL_HOST: ci.docker
      VIRTUAL_PORT: 8080

  worker:
    image: concourse/concourse
    privileged: true
    restart: unless-stopped
    command: worker
    networks:
      - back
    volumes:
      - keys:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: tsa
